apiVersion: v1
kind: ConfigMap
metadata:
  name: db-config
  namespace: microservices-app
data:
  DB_HOST: "postgres-service"
  DB_PORT: "5432"
  DB_NAME: "uploads"
  init.sql: |
    CREATE TABLE IF NOT EXISTS requests (
      id SERIAL PRIMARY KEY,
      backend_name TEXT NOT NULL,
      ts TIMESTAMP DEFAULT NOW(),
      meta JSONB,
      image BYTEA
    );