apiVersion: v1
kind: ResourceQuota
metadata:
  name: microservices-quota
  namespace: microservices-app
spec:
  hard:
    # CPU limits
    requests.cpu: "4"
    limits.cpu: "8"
    
    # Memory limits
    requests.memory: 4Gi
    limits.memory: 8Gi
    
    # Storage limits
    persistentvolumeclaims: "5"
    
    # Pod limits
    pods: "20"
    
    # Service limits
    services: "10"
    services.loadbalancers: "2"