apiVersion: v1
kind: Secret
metadata:
  name: db-secret
  namespace: microservices-app
type: Opaque
stringData:
  POSTGRES_PASSWORD: "mysecretpassword"
  POSTGRES_USER: "postgres"
  POSTGRES_DB: "uploads"